(cl:defpackage beginner_tutorials-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "SUBSTRING"
   "<SUBSTRING-REQUEST>"
   "SUBSTRING-REQUEST"
   "<SUBSTRING-RESPONSE>"
   "SUBSTRING-RESPONSE"
  ))

