/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/catkin_ws/src/beginner_tutorials/msg/DateTime.msg
 *
 */


#ifndef BEGINNER_TUTORIALS_MESSAGE_DATETIME_H
#define BEGINNER_TUTORIALS_MESSAGE_DATETIME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct DateTime_
{
  typedef DateTime_<ContainerAllocator> Type;

  DateTime_()
    : year(0)
    , month()
    , day(0)
    , hour(0)
    , minute(0)
    , seconds(0)  {
    }
  DateTime_(const ContainerAllocator& _alloc)
    : year(0)
    , month(_alloc)
    , day(0)
    , hour(0)
    , minute(0)
    , seconds(0)  {
    }



   typedef int32_t _year_type;
  _year_type year;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _month_type;
  _month_type month;

   typedef int32_t _day_type;
  _day_type day;

   typedef int8_t _hour_type;
  _hour_type hour;

   typedef int8_t _minute_type;
  _minute_type minute;

   typedef int8_t _seconds_type;
  _seconds_type seconds;




  typedef boost::shared_ptr< ::beginner_tutorials::DateTime_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::DateTime_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct DateTime_

typedef ::beginner_tutorials::DateTime_<std::allocator<void> > DateTime;

typedef boost::shared_ptr< ::beginner_tutorials::DateTime > DateTimePtr;
typedef boost::shared_ptr< ::beginner_tutorials::DateTime const> DateTimeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::DateTime_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::DateTime_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/root/catkin_ws/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::DateTime_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::DateTime_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::DateTime_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::DateTime_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::DateTime_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::DateTime_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::DateTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e9ed7f8079280832cde846e0b39652f";
  }

  static const char* value(const ::beginner_tutorials::DateTime_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e9ed7f807928083ULL;
  static const uint64_t static_value2 = 0x2cde846e0b39652fULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::DateTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/DateTime";
  }

  static const char* value(const ::beginner_tutorials::DateTime_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::DateTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 year\n\
string month\n\
int32 day\n\
int8 hour\n\
int8 minute\n\
int8 seconds\n\
";
  }

  static const char* value(const ::beginner_tutorials::DateTime_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::DateTime_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.year);
      stream.next(m.month);
      stream.next(m.day);
      stream.next(m.hour);
      stream.next(m.minute);
      stream.next(m.seconds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct DateTime_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::DateTime_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::DateTime_<ContainerAllocator>& v)
  {
    s << indent << "year: ";
    Printer<int32_t>::stream(s, indent + "  ", v.year);
    s << indent << "month: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.month);
    s << indent << "day: ";
    Printer<int32_t>::stream(s, indent + "  ", v.day);
    s << indent << "hour: ";
    Printer<int8_t>::stream(s, indent + "  ", v.hour);
    s << indent << "minute: ";
    Printer<int8_t>::stream(s, indent + "  ", v.minute);
    s << indent << "seconds: ";
    Printer<int8_t>::stream(s, indent + "  ", v.seconds);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_DATETIME_H
